export const EXPERIENCE = {
  pl: [
    {
      role: "Security Operations Center Analyst",
      company: "IMGW - Instytut Meteorologii i Gospodarki Wodnej",
      period: "paź 2023 – lut 2026",
      duration: "2 lata 5 mies.",
      team: "blue",
      tags: [
        "SIEM",
        "IDS/IPS",
        "Incident Response",
        "Security Monitoring",
        "Detection Thinking",
        "Python",
      ],
      bullets: [
        "Analiza zagrożeń i wykrywanie incydentów bezpieczeństwa w środowisku instytucji państwowej.",
        "Reagowanie na incydenty bezpieczeństwa oraz koordynacja działań naprawczych.",
        "Praca z narzędziami SIEM oraz IDS/IPS w kontekście monitorowania, detekcji i analizy zdarzeń.",
        "Tworzenie dokumentacji po incydentach w sposób zrozumiały dla osób technicznych i decyzyjnych.",
        "Automatyzacja wybranych zadań bezpieczeństwa z użyciem Pythona.",
        "Edukacja użytkowników i wzmacnianie świadomości bezpieczeństwa w organizacji.",
      ],
    },
    {
      role: "Angular Developer",
      company: "IMGW - Instytut Meteorologii i Gospodarki Wodnej",
      period: "lip 2021 – paź 2023",
      duration: "2 lata 4 mies.",
      team: "neutral",
      tags: ["Angular", "RxJS", "TypeScript", "Frontend", "Public Sector"],
      bullets: [
        "Rozwój aplikacji webowych dla środowiska instytucji publicznej.",
        "Praca z Angular, TypeScript oraz RxJS przy tworzeniu interfejsów użytkownika.",
        "Budowanie doświadczenia developerskiego, które obecnie wspiera analizę bezpieczeństwa aplikacji od strony kodu, logiki i architektury.",
      ],
    },
    {
      role: "AI Automation & Prompt Engineer",
      company: "IBPM S.A.",
      period: "2025 – 2026",
      duration: "",
      team: "acc",
      tags: [
        "IBM WatsonX",
        "n8n",
        "LLM Security",
        "Prompt Engineering",
        "AI Automation",
        "Workflow Automation",
      ],
      bullets: [
        "Projektowanie automatyzacji procesów biznesowych z użyciem n8n i AI pipeline'ów.",
        "Praca z modelami językowymi w środowisku IBM WatsonX.",
        "Tworzenie workflowów łączących dane, logikę biznesową, integracje API i modele AI.",
        "Analiza bezpieczeństwa rozwiązań AI - prompt injection, nadmierne zaufanie do modelu, kontrola danych wejściowych i wyjściowych.",
        "Łączenie perspektywy automatyzacji, bezpieczeństwa i praktycznego wdrażania AI w procesach organizacyjnych.",
      ],
    },
    {
      role: "Software Developer",
      company: "Frey · Conscensia (outsourcing)",
      period: "cze 2023 – mar 2025",
      duration: "1 rok 10 mies.",
      team: "neutral",
      tags: ["JavaScript", "TypeScript", "React", "Express.js", "AWS", "DynamoDB", "TDD"],
      bullets: [
        "Rozwój front-endu z użyciem JavaScript, TypeScript oraz React.js.",
        "Praca po stronie back-endu z Express.js, bazami danych SQL oraz DynamoDB.",
        "Wdrażanie i utrzymanie rozwiązań w środowisku AWS.",
        "Praca w podejściu Test-Driven Development oraz automatyzacja testów z użyciem Playwright.",
        "Budowanie praktycznego zrozumienia cyklu życia aplikacji - od kodu, przez testy, po wdrożenie.",
      ],
    },
    {
      role: "Frontend Developer",
      company: "NFOŚiGW - Narodowy Fundusz Ochrony Środowiska",
      period: "lip 2022 – mar 2024",
      duration: "1 rok 9 mies.",
      team: "neutral",
      tags: ["Vue.js", "Vuex", "JavaScript", "JIRA", "REST API"],
      bullets: [
        "Tworzenie zaawansowanych interfejsów użytkownika z użyciem Vue.js dla systemów instytucji publicznej.",
        "Praca przy skalowalnych systemach wewnętrznych oraz integracjach z API.",
        "Zarządzanie stanem aplikacji z użyciem Vuex.",
        "Współpraca w środowisku projektowym z wykorzystaniem JIRA oraz procesów zespołowych.",
      ],
    },
  ],

  en: [
    {
      role: "Security Operations Center Analyst",
      company: "IMGW - Institute of Meteorology and Water Management",
      period: "Oct 2023 – Feb 2026",
      duration: "2 yrs 5 mos",
      team: "blue",
      tags: [
        "SIEM",
        "IDS/IPS",
        "Incident Response",
        "Security Monitoring",
        "Detection Thinking",
        "Python",
      ],
      bullets: [
        "Threat analysis and security incident detection in a government institution environment.",
        "Security incident response and coordination of remediation actions.",
        "Working with SIEM and IDS/IPS tools in the context of monitoring, detection and event analysis.",
        "Creating post-incident documentation understandable to both technical and decision-making audiences.",
        "Automating selected security tasks using Python.",
        "Promoting security awareness and best practices across the organization.",
      ],
    },
    {
      role: "Angular Developer",
      company: "IMGW - Institute of Meteorology and Water Management",
      period: "Jul 2021 – Oct 2023",
      duration: "2 yrs 4 mos",
      team: "neutral",
      tags: ["Angular", "RxJS", "TypeScript", "Frontend", "Public Sector"],
      bullets: [
        "Developing web applications for a public institution environment.",
        "Working with Angular, TypeScript and RxJS to build user interfaces.",
        "Building developer experience that now supports application security analysis from the code, logic and architecture perspective.",
      ],
    },
    {
      role: "AI Automation & Prompt Engineer",
      company: "IBPM S.A.",
      period: "2025 – 2026",
      duration: "",
      team: "acc",
      tags: [
        "IBM WatsonX",
        "n8n",
        "LLM Security",
        "Prompt Engineering",
        "AI Automation",
        "Workflow Automation",
      ],
      bullets: [
        "Designing business process automations using n8n and AI pipelines.",
        "Working with language models in the IBM WatsonX environment.",
        "Building workflows connecting data, business logic, API integrations and AI models.",
        "Analyzing AI solution security - prompt injection, excessive model trust, input/output control and data exposure risks.",
        "Combining automation, security and practical AI implementation in organizational processes.",
      ],
    },
    {
      role: "Software Developer",
      company: "Frey · Conscensia (outsourcing)",
      period: "Jun 2023 – Mar 2025",
      duration: "1 yr 10 mos",
      team: "neutral",
      tags: ["JavaScript", "TypeScript", "React", "Express.js", "AWS", "DynamoDB", "TDD"],
      bullets: [
        "Frontend development using JavaScript, TypeScript and React.js.",
        "Backend work with Express.js, SQL databases and DynamoDB.",
        "Deploying and maintaining solutions in AWS environments.",
        "Working with Test-Driven Development and test automation using Playwright.",
        "Building practical understanding of the application lifecycle - from code and testing to deployment.",
      ],
    },
    {
      role: "Frontend Developer",
      company: "NFOŚiGW - National Fund for Environmental Protection",
      period: "Jul 2022 – Mar 2024",
      duration: "1 yr 9 mos",
      team: "neutral",
      tags: ["Vue.js", "Vuex", "JavaScript", "JIRA", "REST API"],
      bullets: [
        "Building advanced user interfaces with Vue.js for public institution systems.",
        "Working on scalable internal systems and API integrations.",
        "Managing application state using Vuex.",
        "Collaborating in a project environment using JIRA and team delivery processes.",
      ],
    },
  ],
};

export const CERTIFICATIONS = [
  {
    label: "eJPT",
    issuer: "INE Security",
    sub: "eLearnSecurity Junior Penetration Tester",
    year: "2026",
    preset: "gold",
    icon: "Crosshair",
  },
  {
    label: "ICCA",
    issuer: "INE Security",
    sub: "INE Certified Cloud Associate",
    year: "2026",
    preset: "gold",
    icon: "Award",
  },
  {
    label: "AI Security",
    issuer: "TryHackMe",
    sub: "LLM security · prompt injection · AI attack surface",
    year: "2026",
    preset: "gold",
    icon: "BadgeCheck",
  },
  {
    label: "Narzędziownik OSINT 2.0",
    issuer: "Securitum",
    sub: "OSINT · threat intelligence · social media · dark web",
    year: "2026",
    preset: "sekurak",
    icon: "BadgeCheck",
  },
  {
    label: "Sekurak Academy Hacker",
    issuer: "Sekurak",
    sub: "Web Application Security - Hacker",
    year: "2026",
    preset: "sekurak",
    icon: "BadgeCheck",
  },
  {
    label: "Mega Sekurak Hacking Party 2025",
    issuer: "Sekurak",
    sub: "Speaker · cybersecurity conference",
    year: "2025",
    preset: "sekurak",
    icon: "BadgeCheck",
  },

  {
    label: "Sekurak Academy",
    issuer: "Sekurak",
    sub: "Overall defensive and offensive security knowledge",
    year: "2023-2026",
    preset: "sekurak",
    icon: "BadgeCheck",
  },
  {
    label: "Bezpieczeństwo API REST",
    issuer: "Securitum",
    sub: "API recon · HTTP methods · SSRF · JWT · webhooks",
    year: "2024",
    preset: "sekurak",
    icon: "BadgeCheck",
  },
  {
    label: "Zaawansowane bezpieczeństwo sieci",
    issuer: "Securitum",
    sub: "Infrastructure security · Docker · cloud · practical network testing",
    year: "2024",
    preset: "sekurak",
    icon: "BadgeCheck",
  },
];

export const SKILL_CLUSTERS = [
  {
    key: "red",
    skills: [
      "Web Exploitation",
      "Burp Suite",
      "Recon",
      "Nmap",
      "PortSwigger Labs",
      "TryHackMe",
      "Pentest Reporting",
      "API Security",
    ],
  },
  {
    key: "blue",
    skills: [
      "SIEM",
      "Wazuh",
      "IDS/IPS",
      "Incident Response",
      "Security Monitoring",
      "Detection Thinking",
      "Python Automation",
    ],
  },
  {
    key: "dev",
    skills: [
      "Angular",
      "React",
      "Vue.js",
      "TypeScript",
      "Express.js",
      "AWS",
      "DynamoDB",
      "REST API",
    ],
  },
  {
    key: "ai",
    skills: [
      "AI Security",
      "LLM Security",
      "Prompt Engineering",
      "AI Red-Teaming",
      "IBM WatsonX",
      "Prompt Injection",
      "LLM Attack Surface",
    ],
  },
  {
    key: "automation",
    skills: [
      "n8n",
      "Workflow Automation",
      "API Integrations",
      "AI Pipelines",
      "Process Automation",
      "Python Automation",
    ],
  },
  {
    key: "osint",
    skills: [
      "OSINT",
      "Threat Intelligence",
      "Social Media Intelligence",
      "Dark Web Research",
      "Disinformation Analysis",
      "Crypto Transaction Tracing",
    ],
  },
];

export const ABOUT_LINKS = [
  {
    href: "https://www.linkedin.com/in/szymanski-maciej1337/",
    icon: "Link2",
    label: "LinkedIn",
    handle: "Maciej Szymański · szymanski-maciej1337",
    accent: "acc",
  },
  {
    href: "https://tryhackme.com/p/Bonus1337",
    icon: "Target",
    label: "TryHackMe",
    handle: "Bonus1337 · AI Security · active lab progress",
    accent: "red",
  },
  {
    href: "https://sekurak.pl",
    icon: "Radar",
    label: "Sekurak",
    handle: "Insider · speaker · content creator · community",
    accent: "acc",
  },
];
